### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sicko-gl** [glftpd/pftp#1]
Did a clone of pftp. Tried to compile on Ubuntu 16.04.2. 

$ make
cd src;make;cd ..
make[1]: Entering directory '/home/xx/pftp/trunk-vanilla/src'
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS main.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS switchserver.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS tcp.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS displayupdate.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS server.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS bookmark.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS opensitedialog.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS displayhandler.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS keyhandler.cc
g++ -pipe -c -Wall -Wno-unused-result -Wno-write-strings -D_REENTRANT -I../include -D_FORTIFY_SOURCE=2 -fstack-protector-all -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -flto -fPIE -O2 -DTLS tlsutil.cc
g++ -pipe -o pftp-dynamic main.o switchserver.o tcp.o displayupdate.o server.o bookmark.o opensitedialog.o displayhandler.o keyhandler.o tlsutil.o -lssl -lcrypto -DTLS -lpanel -lncurses -ltinfo -lpthread -ldl
cp -f pftp-dynamic ..
g++ -pipe -o pftp-static main.o switchserver.o tcp.o displayupdate.o server.o bookmark.o opensitedialog.o displayhandler.o keyhandler.o tlsutil.o -lssl -lcrypto -DTLS -lpanel -lncurses -ltinfo -lpthread -ldl -static
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/ccFHNr3I.ltrans6.ltrans.o: In function `CServer::LocalGetDirlist()':
<artificial>:(.text+0x2ce): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
<artificial>:(.text+0x2f6): warning: Using 'getgrgid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/ccFHNr3I.ltrans9.ltrans.o: In function `CTCP::GetIP(char*, in_addr*)':
<artificial>:(.text+0xab4): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `_nc_mouse_event':
(.text+0x5d5): undefined reference to `Gpm_GetEvent'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `enable_gpm_mouse':
(.text+0xce2): undefined reference to `Gpm_Close'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `enable_gpm_mouse':
(.text+0xd37): undefined reference to `Gpm_Open'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `enable_gpm_mouse':
(.text+0xd4c): undefined reference to `Gpm_Close'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `_nc_mouse_init':
(.text+0xea7): undefined reference to `gpm_fd'
**/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `mouse_activate':
(.text+0x107b): undefined reference to `gpm_fd'
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'pftp-static' failed
make[1]: *** [pftp-static] Error 1
make[1]: Leaving directory '/home/xx/pftp/trunk-vanilla/src'**

**Comment by glftpd** [comment]
i pushed a change to only build dynamic version by default which should work almost always :)
