### ISSUE TITLE
TLS/SSL error transferring file

### ISSUE THREAD

**Issue by sicko-gl** [glftpd/pftp#2]
did a git clone, compiled up dynamic pftp from the 'trunk-shit' and tried to fxp a file. 
got this error: 

21:44 150 Opening BINARY mode data connection for a.file.r06 (100000000 bytes) using SSL/TLS.
21:44 435 Failed TLS negotiation on data channel (SSL_connect(): (1) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure), disconnected

**Comment by glftpd** [comment]
pftp just tells the servers to send file from one to another. From the error it seems one of the servers is trying to use SSL3 while the other doesnt support SSL 3.
