### ISSUE TITLE
failed   - to create temp file

### ISSUE THREAD

**Issue by ejade** [glftpd/pftp#4]
PFTP throws error after logging in and getting dirlist.
Errormessage: 18:31:12 [debian      ] failed   - to create temp file

looking at strace shows:
open("./ok/pftp.debug.log", O_RDWR|O_CREAT|O_APPEND, 0666) = -1 ENOENT (No such file or directory

In order to reproduce
clone repo on debian jessie
make dynamic
run pftp and connect to ftpserver

**Comment by blixten85** [comment]
Yeah, fix?

**Comment by glftpd** [comment]
and the "ok" directory exists and the file can be created ? can you make an empty one yourself ?

**Comment by blixten85** [comment]
Yes, the folder exist, the file exist, it even writes to it. 

"Tue Dec 24 04:54:45 2019 [23603 ] after keymap
Tue Dec 24 04:54:45 2019 [23603 ] read bookmark id : II@0.11.2mew6+2
Tue Dec 24 04:54:45 2019 [23603 ] id II@0.11.2mew6+2
 was latest"

But this is all it writes. And yet this error.

EDIT:
I add a strace output of ./pftp
https://pastebin.com/5GZAaZ3W

**Comment by glftpd** [comment]
ah, please make sure you change the path from relative to absolute

**Comment by blixten85** [comment]
Where do i do this?

**Comment by glftpd** [comment]
pftp config file, in the vanilla it was .pftpconf if i remember right

**Comment by blixten85** [comment]
like OKAYDIR=/home/xxx/pftp/pftp-shit/ok/ instead of OKAYDIR=./ok ?

EDIT:
Yes now it works!
thx :)

**Comment by glftpd** [comment]
:)
